### ISSUE TITLE
How to find songs and import them in android version?

### ISSUE THREAD

**Issue by BongoMai** [2394425147/maipaddx#1]
Hello! i came across this project and saw that you can play maimai. I see other people download charts but I dont know where to download them as i dont have a QQ account. even if i download i also wouldnt know how to import.

**Comment by stoner616** [comment]
import charts to android/data/com.Reflektone.MaipadDX/files/local/default

**Comment by 2394425147** [comment]
This is a good one! The importing system right now is kind of complicated for new players, so I'll be making a short guide on importing soon
