### ISSUE TITLE
如何在游戏内更改设置

### ISSUE THREAD

**Issue by Fukimes** [2394425147/maipaddx#10]
版本2.0.0.pre.39
游戏内未找到设置界面
以及在此版本发生了标题界面翻译出错的问题
![error](https://user-images.githubusercontent.com/75737878/199011652-3cbd6ed6-8f67-43fe-a0af-5f83e6d71162.jpg)

**Comment by UnrealOfficial** [comment]
请编辑(/storage/emulated/0/Android/data/com.Reflektone.AstroDX/files/)中的settings.json文件来修改设置
