### ISSUE TITLE
What the hell is that??? 

### ISSUE THREAD

**Issue by SashaB456** [2394425147/maipaddx#11]
Where it comes from??? 
![Screenshot_20221117-151552](https://user-images.githubusercontent.com/118451471/202458208-6d86b808-c016-4687-be40-50ec34075809.jpg)

**Comment by SashaB456** [comment]
![Screenshot_20221117-152949](https://user-images.githubusercontent.com/118451471/202459338-5af8cee5-4bf1-4761-9719-b525da5aabb3.jpg)

**Comment by SashaB456** [comment]
![Screenshot_20221117-153001](https://user-images.githubusercontent.com/118451471/202459484-fadf27b1-a8f0-442a-8ce1-e30a4c40be11.jpg)

**Comment by 2394425147** [comment]
try `copy to clipboard`

**Comment by SashaB456** [comment]
> i think this might be a new problem! if you could reproduce it, try clicking inside the first error and sending the copied data here, this might help me track down the issue further thanks!
This glitch is happening when you run this app. And also, I wanted to show you Hachi Hachi(also mobile maimai), that had special songs, but this game closed their servers. If you want more details, then I'll give you video.
Gameplay : https://youtu.be/qcOfXfMhNTE(I can't place notes between buttons and rotate the circle). 
What happend to this game : https://youtu.be/gVgT-ZU2mi8

**Comment by SashaB456** [comment]
> 

Texture creation failed. 'ShadowAuto' is not supported for Render usage on this platform. Use 'SystemInfo.IsFormatSupported' C# API to check format support.

 #0 0x7828690f54 (libunity.so) ? 0x0
 #1 0x7828b186a0 (libunity.so) ? 0x0
 #2 0x782838b90c (libunity.so) ? 0x0
 #3 0x782838b7fc (libunity.so) ? 0x0
 #4 0x7827821a44 (libil2cpp.so) ? 0x0
 #5 0x7827826ccc (libil2cpp.so) ? 0x0
 #6 0x7827716790 (libil2cpp.so) ? 0x0
 #7 0x782770f9f4 (libil2cpp.so) ? 0x0
 #8 0x78276f5498 (libil2cpp.so) ? 0x0
 #9 0x78276f4eb0 (libil2cpp.so) ? 0x0
 #10 0x78277671cc (libil2cpp.so) ? 0x0
 #11 0x7827729d60 (libil2cpp.so) ? 0x0
 #12 0x7827851f7c (libil2cpp.so) ? 0x0
 #13 0x78278526a0 (libil2cpp.so) ? 0x0
 #14 0x7827852ef4 (libil2cpp.so) ? 0x0
 #15 0x7826260ec0 (libil2cpp.so) ? 0x0
 #16 0x7826260e0c (libil2cpp.so) ? 0x0
 #17 0x78285a2ac0 (libunity.so) ? 0x0
 #18 0x78285b1d18 (libunity.so) ? 0x0
 #19 0x78284a92dc (libunity.so) ? 0x0
 #20 0x78288f0ad4 (libunity.so) ? 0x0
 #21 0x78288f102c (libunity.so) ? 0x0
 #22 0x78284d4a8c (libunity.so) ? 0x0
 #23 0x78284cbdb8 (libunity.so) ? 0x0
 #24 0x78284cbdf8 (libunity.so) ? 0x0
 #25 0x78284cc084 (libunity.so) ? 0x0
 #26 0x7828631750 (libunity.so) ? 0x0
 #27 0x7828648ad4 (libunity.so) ? 0x0
 #28 0x7829614b1c (base.odex) ? 0x0

**Comment by SashaB456** [comment]
NullReferenceException: Object reference not set to an instance of an object.

UnityEngine.Rendering.RTHandleSystem.Alloc (System.Int32 width, System.Int32 height, System.Int32 slices, UnityEngine.Rendering.DepthBits depthBufferBits, UnityEngine.Experimental.Rendering.GraphicsFormat colorFormat, UnityEngine.FilterMode filterMode, UnityEngine.TextureWrapMode wrapMode, UnityEngine.Rendering.TextureDimension dimension, System.Boolean enableRandomWrite, System.Boolean useMipMap, System.Boolean autoGenerateMips, System.Boolean isShadowMap, System.Int32 anisoLevel, System.Single mipMapBias, UnityEngine.Rendering.MSAASamples msaaSamples, System.Boolean bindTextureMS, System.Boolean useDynamicScale, UnityEngine.RenderTextureMemoryless memoryless, UnityEngine.VRTextureUsage vrUsage, System.String name) (at <00000000000000000000000000000000>:0)
UnityEngine.Rendering.RTHandles.Alloc (System.Int32 width, System.Int32 height, System.Int32 slices, UnityEngine.Rendering.DepthBits depthBufferBits, UnityEngine.Experimental.Rendering.GraphicsFormat colorFormat, UnityEngine.FilterMode filterMode, UnityEngine.TextureWrapMode wrapMode, UnityEngine.Rendering.TextureDimension dimension, System.Boolean enableRandomWrite, System.Boolean useMipMap, System.Boolean autoGenerateMips, System.Boolean isShadowMap, System.Int32 anisoLevel, System.Single mipMapBias, UnityEngine.Rendering.MSAASamples msaaSamples, System.Boolean bindTextureMS, System.Boolean useDynamicScale, UnityEngine.RenderTextureMemoryless memoryless, UnityEngine.VRTextureUsage vrUsage, System.String name) (at <00000000000000000000000000000000>:0)
UnityEngine.Experimental.Rendering.RenderGraphModule.RenderGraphDefaultResources..ctor () (at <00000000000000000000000000000000>:0)
UnityEngine.Experimental.Rendering.RenderGraphModule.RenderGraph..ctor (System.String name) (at <00000000000000000000000000000000>:0)
UnityEngine.Rendering.Universal.UniversalRenderPipeline..ctor (UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset asset) (at <00000000000000000000000000000000>:0)
UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset.CreatePipeline () (at <00000000000000000000000000000000>:0)
UnityEngine.Rendering.RenderPipelineAsset.InternalCreatePipeline () (at <00000000000000000000000000000000>:0)
UnityEngine.Rendering.RenderPipelineManager.PrepareRenderPipeline (UnityEngine.Rendering.RenderPipelineAsset pipelineAsset) (at <00000000000000000000000000000000>:0)
UnityEngine.Rendering.RenderPipelineManager.DoRenderLoop_Internal (UnityEngine.Rendering.RenderPipelineAsset pipe, System.IntPtr loopPtr, UnityEngine.Object renderRequest) (at <00000000000000000000000000000000>:0)
UnityEngine.Rendering.RenderPipelineManager:DoRenderLoop_Internal(RenderPipelineAsset, IntPtr, Object)
Second error

**Comment by SashaB456** [comment]
And what is the problem withb issue #6?

**Comment by SashaB456** [comment]
![Screenshot_20221117-174106](https://user-images.githubusercontent.com/118451471/202491192-cd53bacb-46ac-4800-8c20-a1a706e93c30.jpg)
...
