### ISSUE TITLE
2.0.0.beta在华为Harmony OS中 .axco后缀无法关联到AstroDX应用

### ISSUE THREAD

**Issue by Fuathear** [2394425147/maipaddx#12]
2.0.0.beta在华为Harmony OS中 .axco后缀无法关联到AstroDX应用，自动导入方法无法使用。

**Comment by 2394425147** [comment]
2.0.beta.pre开始暂时取消了文件按后缀名导入的方法
这样子

**Comment by 2394425147** [comment]
会在prebeta期结束前补上的uwu
