### ISSUE TITLE
2.0.0.bata.pre.87版本曲目导入无法正常进入曲目

### ISSUE THREAD

**Issue by kefeng241** [2394425147/maipaddx#15]
进入曲目后会直接结束曲目并回到选区界面，cmd会弹出错误“NullReferenceException: Object reference not set to an instance of an object.”

**Comment by kefeng241** [comment]
使用的是Harmony OS 3.0.0.163

**Comment by cubruce1103** [comment]
也許該難易度沒有任何note
如果有note，有可能是譜面有問題
更到pre93再點開譜面看一下，應該會回報哪邊出錯
