### ISSUE TITLE
暂停再继续后谱面与音频错位

### ISSUE THREAD

**Issue by di404** [2394425147/maipaddx#16]
暂停后点击继续按钮恢复，谱面“倒退”到当前存在的音符刚刚出现时的时刻，而音频照常播放，导致谱面与音频不同步。

**Comment by MuuuShin** [comment]
一段产生此现象的录屏：
https://www.bilibili.com/video/BV1vX4y1C7rR

**Comment by MuuuShin** [comment]
> 一段产生此现象的录屏： https://www.bilibili.com/video/BV1vX4y1C7rR

没有偏题啊==   这段录屏的后半段就是演示音频不同步的效果
