### ISSUE TITLE
[New function suggestion] Note falling speed adjustion

### ISSUE THREAD

**Issue by rong-xiaoli** [2394425147/maipaddx#22]
Some may perfer faster falling speed (like me), and others perfer slower. I suggest adding a drag bar to adjust this, or refer to maimai DX which marks the speed of the note.

**Comment by beerpiss** [comment]
Already a thing, edit `Android/data/com.Reflektone.AstroDX/files/settings.json` (Android) or `AstroDX/settings.json` (iOS) manually.

The option is under `gameplay -> tap_speed`.

For a list of settings and what they mean, refer to [this gist](https://gist.github.com/beerpiss/653d5a64f4b75c6910f5ddf222daf8b4)

A setting menu will be added eventually (hopefully next update).

**Comment by 2394425147** [comment]
Hi, this feature is currently only accessible via the settings.json file as the in-game ui hasn't been implemented, check `gameplay.tap_speed` and `gameplay.touch_speed`, then you can adjust the values to any decimal value to your liking.

We're working on this feature for 2.0.0.beta.pre.90, so it should be easier to do so soon.

Thanks!

**Comment by rong-xiaoli** [comment]
OK thanks.
