### ISSUE TITLE
v2.0.pre.89 Android 13 I/O 权限错误

### ISSUE THREAD

**Issue by EDTA-gif** [2394425147/maipaddx#23]
* 设备：红米K40Pro
* 系统：MIUI 14 EU 14.0.3.0稳定版（Android 13）
* 游戏版本：v2.0.0.beta.pre.89
* bug：启动后游戏提示无IO权限，打开游戏界面未识别到歌曲，软件未请求存储权限

![QQ图片20230206160256](https://user-images.githubusercontent.com/57220620/216917449-bfe3cd8c-7b61-488e-a925-9c735840b671.jpg)
![QQ图片20230206160301](https://user-images.githubusercontent.com/57220620/216917455-3f66f1dd-6520-4336-843f-bf067e6ef8bf.jpg)

**Comment by 2394425147** [comment]
你好！
这个问题大概率是由文件管理器权限高于游戏默认权限导致的，可以尝试换一个比如ZArchiver的第三方工具再导入
