### ISSUE TITLE
FAST/LATE数量显示错误

### ISSUE THREAD

**Issue by MizuIro-H** [2394425147/maipaddx#24]
![QQ截图20230301181508](https://user-images.githubusercontent.com/123630455/222110307-db88f3cd-7528-4fe6-9d21-927096ce37c0.png)
没有击打音符的MISS被错误地视作FAST ，而且PERFECT GREAT GOOD的FAST/LATE个数不显示。

**Comment by 2394425147** [comment]
这个问题在2.0.0.beta.pre.94修好了，感谢uwu
