### ISSUE TITLE
无法在32位的Arm设备上运行

### ISSUE THREAD

**Issue by WYH2004-MC** [2394425147/maipaddx#26]
**Describe the bug**
使用32位Arm的安卓设备运行时发生闪退

**Device specs**
 - Device: Xiaomi MIPad 1
 - OS: Android 7.1.1

**Comment by Soneoylys** [comment]
不是Bug, 暂时没有给32位设备添加支持的计划, 最低设备要求为Apple A9/Exynos 8890/Snapdragon 835或同等级以上的SoC, 内存要求为2G以上
