### ISSUE TITLE
背景视频播放错误

### ISSUE THREAD

**Issue by XaopMiao** [2394425147/maipaddx#27]
设备：iPad9
系统版本：iPadOS16.1.1
beat版本：94
问题：背景视频在播放时会强制1:1播放
![IMG_0249](https://user-images.githubusercontent.com/127759673/224724630-76f5ee9c-938f-49a5-9832-ccfa2919a88a.PNG)
![IMG_0250](https://user-images.githubusercontent.com/127759673/224724682-c26f1e7b-743b-42e8-b28f-cadbfc064fde.PNG)

**Comment by 2394425147** [comment]
其实是为了填充满整个背景故意这样做的，后期会有选项供调整uwu
