### ISSUE TITLE
iOS版本有时会漏键

### ISSUE THREAD

**Issue by StarWish686** [2394425147/maipaddx#28]
设备:iPad mini 4
系统版本:iPadOS 15
游戏版本:2.0.0（95）
有时在玩的时候，已经做出了对应的动作，但是程序没有识别到动作，最后漏了键。这个问题是平板的性能问题吗？希望作者能解答下

**Comment by Soneoylys** [comment]
大概是平板性能问题, 本地使用两台配置不一样的设备均无法复现

测试设备1: iPad Pro 12.9‑in. (5th generation)
系统版本: iOS 15.3 (19D50)

测试设备2: iPad Pro 11‑in. (4th generation)
系统版本: iOS 16.4.1 (20E252)
