### ISSUE TITLE
是否可以编译x86版本的apk供Android_x86使用

### ISSUE THREAD

**Issue by DMB-codegang** [2394425147/maipaddx#29]
我目前的平板的dell的一台x86平板
在这台平板上安装了BlissOS 15.8.5
希望可以编译一份适用于Android_x86的安装包
非常感谢！

**Comment by 2394425147** [comment]
可能得试一下，unity目前好像只提供armv7和arm64的编译，但是如果找到办法有机会编译的话我们会附在release中，感谢uwu

**Comment by DMB-codegang** [comment]
有一款叫Sky Studio的软件，也是用unity编译，但是它是Target SDK 33，因此被成功安装和使用

**Comment by Soneoylys** [comment]
Unity不支持target Android amd64, 而Android i386已经在2019.3以及更新版本中被移除, 我们正在使用的版本是最新的LTS, 故无法完成这个请求, 抱歉
Unity关于Android i386 deprecated的说明: https://blog.unity.com/technology/android-support-update-64-bit-and-app-bundles-backported-to-2017-4-lts
