### ISSUE TITLE
Access to Score Files is Denied

### ISSUE THREAD

**Issue by tutuw002** [2394425147/maipaddx#3]
![Screenshot_20220113-173329721](https://user-images.githubusercontent.com/17723450/149304111-cdb04b48-2de3-4699-a1cb-66fedbfe00fc.jpg)
Phone used: Asus ROG Phone 5S
Android: 11
Version: 1.1rc2.2

**Comment by 2394425147** [comment]
Ooh... This can be painful sometimes. As far as we know, this is a problem with your file manager of choice when you imported the chart files. This is a pretty common problem though, so don't worry. A solution is to try an alternative file manager and re-import the chart, or use a PC to re-import the files.
