### ISSUE TITLE
Vivo pad2 游戏运行异常

### ISSUE THREAD

**Issue by def-saizi-baka** [2394425147/maipaddx#31]
#### Vivo pad2 游戏运行异常与帧率问题
1. 2.0.0 pre63 之后所有版本中 打开后整体时不时慢倍速, 包括音乐, 铺面(下落速度也会随着音频卡顿时快时慢)和以及系统界面的背景音
2. 刷新率也有问题, 无法一直保持在120帧, 经常刚打开时是120, 一会后自动变为60或 30

**Comment by Soneoylys** [comment]
使用了AOSP中的标准API, 国产厂商的AOSP皮肤(如MIUI HarmonyOS等)可能会对其进行魔改, 建议联系设备制造商

**Comment by def-saizi-baka** [comment]
> 使用了AOSP中的标准API, 国产厂商的AOSP皮肤(如MIUI HarmonyOS等)可能会对其进行魔改, 建议联系设备制造商

好的, 感谢回复

**Comment by def-saizi-baka** [comment]
提供一个折中解决方案,在虚拟机运行(我的设备是 光速虚拟机 安卓10), 高刷, 音频都解决了, 就是音频延迟在有线的情况下为+300ms左右
