### ISSUE TITLE
音频在暂停后会与铺面不同步

### ISSUE THREAD

**Issue by MuuuShin** [2394425147/maipaddx#32]
**Describe the bug**
如题

**To Reproduce**
1.进入游戏，然后在播放几秒后，暂停。
2.随机时间后，开始游戏，铺面与音乐不同步。
暂停时间貌似不会影响到音乐与铺面之间的时间差。
不同步的现象足够明显，约在3秒以上
应该是音乐快于铺面

**Device specs**
 - Device: iPad air 4
 - OS: ios15.7.1
 - Version 2.0.0 PRE95

**Comment by Soneoylys** [comment]
Duplicate with #16
与上述issue重复, 感谢你对详细信息的补充

**Comment by MuuuShin** [comment]
> Duplicate with #16 与上述issue重复, 感谢你对详细信息的补充

好的，谢谢！

**Comment by Soneoylys** [comment]
详见#16
