### ISSUE TITLE
[Bug?]暂停时左下角小窗播放bga

### ISSUE THREAD

**Issue by MuuuShin** [2394425147/maipaddx#33]
**Describe the bug**
如题

**To Reproduce**
1.暂停一个带有bga的游戏
2.左下角小窗可能继续播放bga

**Device specs**
 - Device: iPad air 4
 - OS: ios15.7.1
 - Version 2.0.0 PRE95

**Comment by Soneoylys** [comment]
请提供游戏版本, 设备名称, 以及AOSP版本等详情

**Comment by MuuuShin** [comment]
> 请提供游戏版本, 设备名称, 以及AOSP版本等详情

已做补充。

**Comment by Soneoylys** [comment]
更新Build 96后仍然存在这个问题吗?

**Comment by MuuuShin** [comment]
> 更新Build 96后仍然存在这个问题吗?
已更新。请看这个视频：
https://www.bilibili.com/video/BV1vX4y1C7rR

**Comment by 2394425147** [comment]
2.0.0.pre.beta.96.9应该解决了，后续还会继续跟进解决可能引发的相关问题，感谢！
