### ISSUE TITLE
增加正解音偏移

### ISSUE THREAD

**Issue by MuuuShin** [2394425147/maipaddx#34]
**Is your feature request related to a problem? Please describe.**
目前的正解音只能设置音量，而不能设置偏移，导致在调整了音频偏移和打击偏移情况下，打击音明显与音乐对不齐。

**Describe the solution you'd like**
增加一个正解音偏移选项。

**Describe alternatives you've considered**
音频偏移和打击偏移调回0可以解决这个问题，但是明显音频偏移和打击偏移的准确更重要。

**Comment by 2394425147** [comment]
打算在2.0.0.pre.beta.96.11直接通过-offset来自动弥补延迟，应该可以解决这个问题
目前测试效果还可以uwu
