### ISSUE TITLE
增加变速

### ISSUE THREAD

**Issue by MuuuShin** [2394425147/maipaddx#35]
**Is your feature request related to a problem? Please describe.**
1.0有的，2.0砍了，希望加回来，对练习还是蛮重要的。

**Describe the solution you'd like**
加变速

**Comment by 2394425147** [comment]
这个可以通过Mod 》 Timewarp修改了，可以升级96.7看一下

**Comment by MuuuShin** [comment]
> 这个可以通过Mod 》 Timewarp修改了，可以升级96.7看一下

好的
草 我刚发issue版本就更新了

**Comment by fork16** [comment]
变速正解音和音频延迟都不对了。请问你也是这样吗
