### ISSUE TITLE
Yeah……new here,sorry.

### ISSUE THREAD

**Issue by REB0225** [2394425147/maipaddx#37]
![IMG_3253](https://github.com/2394425147/maipaddx/assets/134243311/cda2c908-83d6-4ca5-b085-2679172b96a5)

Later chapater……
But where……

**Comment by DavidScann** [comment]
Pretty much every custom chart you make that works in MajdataEdit will work in AstroDX (with a few exceptions regarding syntax), so don't worry. Just drop it into the game folder then enjoy!

**Comment by REB0225** [comment]
![IMG_3340](https://github.com/2394425147/maipaddx/assets/134243311/091a47e6-bc5d-4366-bfab-a422eb72e9d3)
but it looks like this. How do I copy it and do I need to find the song by my own?

**Comment by Soneoylys** [comment]
I'd like to recommend you to join our community like Discord to get support, some of our fantastic community members were written detailed tutorials in there.
