### ISSUE TITLE
ipad air 4在竖屏游玩途中暂停退出会死机

### ISSUE THREAD

**Issue by Heraclesy** [2394425147/maipaddx#40]
**Describe the bug**
ipad air 4在竖屏游玩途中暂停退出会死机

**Expected behavior**
ipad air 4在竖屏游玩途中暂停点按退出键后，页面卡在暂停按钮，此时触摸屏幕可以切换歌曲，且此时锁屏后屏幕熄灭设备在继续播放歌曲，无法亮屏。过一段时间后打开平板进入应用才会回到选歌界面。

**Screenshots**
无，如需要可以录像。

**Device specs**
 - Device: ipad air 4
 - OS: ipad os 16.1(20B82)
 - Version 2.0.0(96)

**Comment by Soneoylys** [comment]
使用iPad Pro 2021 (8G RAM) with iOS 15.3, iPad Pro 2022 (6G RAM) with iOS 16.2
均无法复现, 请考虑上传视频?

**Comment by Heraclesy** [comment]
> 
你好，今天我尝试复现了一下。当ipad打开横向方向锁定，进入游戏并选择竖屏游戏，退出就会死机。如果不开方向锁定则没有问题。

**Comment by Soneoylys** [comment]
感谢您追加的信息！
我们今天重新用上述设备按照视频中的步骤尝试复现了这个BUG，但仍无法复现
在查阅过代码后，发现了一处可能由于CPU性能导致的资源加载不完整的错误，在最新的版本里已经尝试进行了优化
但由于开发组使用的设备均无法复现这个BUG，还请您等待iOS的Build99发布后再进行尝试
若更新到Build99后仍出现这个问题，还请您继续向我们反馈，谢谢！
