### ISSUE TITLE
部分安卓设备音频卡顿撕裂

### ISSUE THREAD

**Issue by BluesDawn576** [2394425147/maipaddx#49]
**Describe the bug**
不正确的dsp buffer导致部分安卓设备音频卡顿撕裂

**To Reproduce**
由后台切至前台，锁屏，系统弹窗都会出现此问题。
2.0.0.beta.pre.98.5 版本打开应用就会音频撕裂，打开 Graphy 重启却恢复正常（玄学）。

**Expected behavior**
可以考虑添加调整 dsp buffer 的选项

**Device specs**
 - Device: 联想拯救者Y700 2022
 - OS: Android 12
 - Version 2.0.0.beta.pre.98.5

**Comment by Carrot-09** [comment]
iqoo pad也有此情况。经过逐一测试2.0.0.pre.beta.64及以后的版本都会出现音频撕裂，2.0.0.pre.beta.63之前则不会。

**Comment by Carrot-09** [comment]
游玩关卡时谱面和音乐一起卡顿，忽快忽慢，顺便一提这种音频卡顿是游戏本身的卡顿，不仅仅出现在游玩关卡的时候。

**Comment by Soneoylys** [comment]
这个不是程序本身的问题
是部分国产魔改皮肤对原生API的兼容性有问题
但我们开发组内没有这种魔改皮肤的设备 故无法复现
目前唯一的解决方案是把DSP buffer增加的很大
可能在未来会重新添加DSP buffer的选项或重写Native middleware

**Comment by Soneoylys** [comment]
对于暂时的解决方案 可以参考#31
