### ISSUE TITLE
关于adx的一些问题

### ISSUE THREAD

**Issue by cold-QAQ** [2394425147/maipaddx#50]
请问下每一个版本之间多少天更新一次，ios端何时环大陆上架，以及ios端测试名额是否可以增多些？

**Comment by Soneoylys** [comment]
因为是业余开发者，我们没有任何更新周期和计划
最近已经在考虑加开一个新的TestFlight测试组
iOS的上架需要等游戏的大部分功能完成之后在做考量 目前没有ETA
谢谢您！
