### ISSUE TITLE
在一些情况下AstroDX会出现卡死的情况

### ISSUE THREAD

**Issue by charassss** [2394425147/maipaddx#53]
**Describe the bug**
使用吸血模式时，点击重启有小概率会卡死，astrodx无任何相应

**To Reproduce**
1.如上

**Expected behavior**
可正常重试、游玩

**Device specs**
 - Device: iPad Air 2021
 - OS: ipadOS 17.0.3
 - Version 2.0.0 testflight group A

**Comment by Soneoylys** [comment]
请你重新安装游戏尝试一下？

**Comment by charassss** [comment]
> 请你重新安装游戏尝试一下？

在更新了最新版本后不会触发了
