### ISSUE TITLE
在同时击打大量touch时易造成卡死、touch全部被吃掉

### ISSUE THREAD

**Issue by charassss** [2394425147/maipaddx#55]
**Describe the bug**
如标题

**Device specs**
 - Device: iPad Air 2021
 - OS: iOS 17.0.3
 - Version 2.0.0 build99

**Comment by Soneoylys** [comment]
可能与#52重复
需要更详细的log或behavior的视频

**Comment by charassss** [comment]
> 可能与#52重复 需要更详细的log或behavior的视频

在更新了最新版本后不会触发了

补充:与#52表现不一致，是astrodx先卡顿，然后恢复的时候touch已经灰了
