### ISSUE TITLE
Regarding whether AstroDX Source Code can be provided for personal use.

### ISSUE THREAD

**Issue by 4rNe5** [2394425147/maipaddx#56]
Hello, I’m Common User of AstroDX.

First, Thank You For develop AstroDX Client in Best Quality.

But, I have Small Problem.
I Use My iPad to Play Rhythm Game. But, The TestFlight Of AstroDX is Full, And I can install AstroDX-iOS On My iPad.

But fortunately, I am an iOS developer with an Apple Developer Membership.

My question and request is whether I can receive the code for AstroDX for personal use or so that I can use my Membership Account to make additional TestFlight distributions.

Thank you for reading, and I look forward to your positive response.

**Comment by 4rNe5** [comment]
# If you can't be bothered to read, please take a look at this
***
I would like to receive code for personal use or support additional TestFlight positions for the project through my Developer Membership.

**Comment by xhayper** [comment]
The game contains paid assets and the source code can't be open sourced, some part of the game has been made open sourced.

**Comment by 4rNe5** [comment]
Then, I Can Contribute This Project To Make New TestFlight Group To Use My Account?
