### ISSUE TITLE
进游戏声音卡顿，重启后解决问题

### ISSUE THREAD

**Issue by Dalieba0502** [2394425147/maipaddx#60]
**Describe the bug**
游戏版本：v2.0.0.beta.pre.99.exp.19
进游戏音画卡顿，声音撕裂，时好时坏
重启也解决不了了
不知道是不是天玑的适配问题，soc是天玑9000+

**To Reproduce**
1.打开游戏
2.音画卡顿
3.重启后依旧卡顿

**Expected behavior**
我只希望它不卡顿就好了，一卡一卡的根本没法玩
**Screenshots**
没法提供
**Device specs**
 - Device: [e.g. iQOO pad]
 - OS: [e.g. Android13]
 - Browser [vivo browser]
 - Version [17.3.52.0]

**Additional context**

**Comment by Dalieba0502** [comment]
现在重启也不行了（悲）

**Comment by Soneoylys** [comment]
不能复现，请补充模板中的信息。

**Comment by Dalieba0502** [comment]
Uploading video_20231201_093007_edit.mp4…

**Comment by Dalieba0502** [comment]
https://github.com/2394425147/maipaddx/assets/136986367/022167c9-4bdc-430f-bf4c-ea0b48195efe

bug复现

**Comment by Dalieba0502** [comment]
> video_20231201_093007_edit.mp4 
> bug复现

@Soneoylys

**Comment by Soneoylys** [comment]
issue重复 请参考 #49 #31 

中国产Android设备魔改AOSP中的native audio标准实现，不在我们的控制范围内
开发组内没有人正在使用此类魔改Android皮肤，所以也无法进行针对性的开发
我们正在准备重写音频组件，*可能会*解决这个问题，但无法保证效果

暂时解决方案可以参考 #31 （未验证是否有效）
