### ISSUE TITLE
Unable to play audio on Mi Pad 5

### ISSUE THREAD

**Issue by Error063** [2394425147/maipaddx#66]
**Describe the bug**
在小米平板5上无法播放音频

**To Reproduce**
1.在小米平板5上无法播放音频

**Expected behavior**
正常播放音频

**Screenshots**

**Device specs**
 - Device: [e.g. iPhone6] Xiaomi Pad 5 (nabu)
 - OS: [e.g. iOS8.1] HyperOS 1.0.24.1.1(ZXL) Android 14
 - Browser [e.g. stock browser, safari] Microsoft Edge
 - Version [e.g. 22] 2.0.0.beta.pre.98.5

**Additional context**
不知道是移植作者的问题还是应用的问题，其他应用的音频可以正常播放

**Comment by Error063** [comment]
补充：在官方ROM （MIUI Pad 14.0.7 Android 13）上仍然无法播放音频，这应该是应用的问题

**Comment by Error063** [comment]
> 补充：在官方ROM （MIUI Pad 14.0.7 Android 13）上仍然无法播放音频，这应该是应用的问题

重置应用数据就行了

**Comment by Soneoylys** [comment]
issue重复 请参考 #49 #31 

中国Android设备魔改AOSP中的native audio标准实现，不在我们的控制范围内
开发组内没有人正在使用此类魔改Android皮肤，所以也无法进行针对性的开发
我们正重写音频组件，并且已接近完成，可能会解决这个问题

暂时解决方案可以参考 #31
