### ISSUE TITLE
maidata.txt检查报错信息有误

### ISSUE THREAD

**Issue by Eternal973** [2394425147/maipaddx#74]
**Describe the bug**
 - Version: v2.0.0.beta.pre.98.5
点击Let's go!按钮后检查maidata.txt出现报错，但显示的错误位置与该行预览不对应，如图
![5a23f1fc81324f22828e8a89c7cc4f5a](https://github.com/2394425147/maipaddx/assets/51935482/5b9175a6-5c29-467b-98d5-96c4a3b04f66)

**To Reproduce**
1.在maidata.txt包含问题的行前加入一个空行
2.运行并尝试游玩，产生报错

如果包含1.中的空行，即
maidata.txt
19 |（空行）
20 |（含有语法错误的行）
21 |（正常的行）
则报错信息显示
Line 20 - （实际为21行的正常行）

如果不包含1.中的空行，即
maidata.txt
19 |（含有语法错误的行）
20 |（正常的行）
则报错信息显示
Line 19 - （含有语法错误的Line 19）

*很多谱师在制作自制谱的时候喜欢在不同难度谱面或不同bpm段落之间加入空行，如此bug不修复将对谱面错误处定位造成一定影响，不能在AstroDX中发现问题原因。*

**Describe the bug**
 - Version: v2.0.0.beta.pre.98.5
Checking maidata.txt after clicking the Let's go! button results in an error, but the error location shown does not correspond to the preview of the line, as shown here
![5a23f1fc81324f22828e8a89c7cc4f5a](https://github.com/2394425147/maipaddx/assets/51935482/5b9175a6-5c29-467b-98d5-96c4a3b04f66)

**To Reproduce**
Steps to reproduce the behavior.
1. Add a blank line before the line in maidata.txt that contains the problem.
2. Run and try to play, generate an error report

If the blank line in 1. is included, i.e.
maidata.txt
19 | (empty line)
20 | (lines containing syntax errors)
21 | (normal line)
then the error message displays
Line 20 - (normal line that is actually Line 21)

If the blank line in 1. is not included, i.e.
maidata.txt
19 | (line containing syntax error)
20 | (normal line)
then the error message displays
Line 19 - (Line 19 with syntax error)

*Many note designers like to add blank lines between different difficulty scores or different bpm passages when making their own works. If this bug is not fixed, it will affect the location of the syntax errors and the cause of the problem cannot be found correctly in AstroDX. *

**Comment by Soneoylys** [comment]
感谢反馈, 我们会在未来版本中修复

Thanks for reporting issue, we'll fix this in future versions.
