### ISSUE TITLE
android14 After launching the game, the 'Android/data/com.Reflektone.AstroDX' folder cannot be generated

### ISSUE THREAD

**Issue by chunliangv87** [2394425147/maipaddx#75]
启动软件后，’Android/data‘中无法找到‘com.Reflektone.AstroDX’文件夹
红魔9pro android版本14 RedMagicOS9.0.21MR_NX769J
After starting the software, the 'com.Reflektone.AstroDX' folder cannot be found in 'Android/data'
Red Magic 9pro android version 14 RedMagicOS9.0.21MR_NX769J

**Comment by DavidScann** [comment]
https://rentry.org/adx_android#android-12-a-pain-in-the-ass-but-still-has-workarounds

This guide should help you solve your issues.

**Comment by Soneoylys** [comment]
Tested on my Samsung, the guide works.
