### ISSUE TITLE
Game doesn't function after importing charts

### ISSUE THREAD

**Issue by sa-ka-na114514** [2394425147/maipaddx#76]
如题，再导入谱面后进入游戏会发生报错![image](https://github.com/2394425147/maipaddx/assets/113164611/250ec7fc-840c-40ee-b1c1-121ea2ed2dbb)
只有删除cache文件才能正常进入游戏，但是游玩记录会丢失，且每次退出后再进入都会这样，但是只要levels文件夹里没有谱面就没有问题

设备：ipad pro2020
游戏是通过自签ipa文件下载的

**Comment by Soneoylys** [comment]
请通过TestFlight重新下载再试试?
